# WARNING: DO NOT COMMIT THIS FILE TO VERSION CONTROL
# Create a local copy for development: cp config.example.yaml config.yaml

target_url: "https://artificialanalysis.ai/leaderboards/providers/prompt-options/single/medium_coding?deprecation=all"
output_csv_path: "data/leaderboard.csv"