# Configuration file

# The Artificial Analysis URL to scrape the leaderboard data from. In case of different leaderboard queries, just update this URL.
## Default: "https://artificialanalysis.ai/leaderboards/providers/prompt-options/single/medium_coding?deprecation=all"
target_url: "https://artificialanalysis.ai/leaderboards/providers/prompt-options/single/medium_coding?deprecation=all"

# The path to save the scraped leaderboard data to.
output_csv_path: "data/leaderboard.csv"